//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Localization.ExceptionsHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradise.Localization.ExceptionsHandling.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application secret is missing. Check the configuration..
        /// </summary>
        internal static string ApplicationSecretMissing {
            get {
                return ResourceManager.GetString("ApplicationSecretMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template subject is in invalid state. Subject placeholder is &apos;null&apos;, but text placeholders number is greater than 0, which leads to impossibility of subject formatting..
        /// </summary>
        internal static string EmailTemplateSubjectInInvalidState {
            get {
                return ResourceManager.GetString("EmailTemplateSubjectInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cast an object of type &apos;{0}&apos; into an object of type &apos;{1}&apos;..
        /// </summary>
        internal static string FailedToCast {
            get {
                return ResourceManager.GetString("FailedToCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateInstanceOfType {
            get {
                return ResourceManager.GetString("FailedToCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize into the instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDeserialize {
            get {
                return ResourceManager.GetString("FailedToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The clock worker&apos;s interval can only be equal to one day..
        /// </summary>
        internal static string InvalidClockWorkerInterval {
            get {
                return ResourceManager.GetString("InvalidClockWorkerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid email address..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; is in invalid state. Column name: &apos;{1}&apos;, value: &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidEntityState {
            get {
                return ResourceManager.GetString("InvalidEntityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information: .
        /// </summary>
        internal static string InvalidEntityStateAdditionalInformation {
            get {
                return ResourceManager.GetString("InvalidEntityStateAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment name &apos;{0}&apos; is not valid. Available options are: {1}..
        /// </summary>
        internal static string InvalidEnvironmentName {
            get {
                return ResourceManager.GetString("InvalidEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of type &apos;{0}&apos; does not provide public parameterless constructor..
        /// </summary>
        internal static string InvalidEqualityComparerConstructor {
            get {
                return ResourceManager.GetString("InvalidEqualityComparerConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of type &apos;{0}&apos; is not assignable to &apos;IEqualityComparer&lt;T&gt;&apos;..
        /// </summary>
        internal static string InvalidEqualityComparerType {
            get {
                return ResourceManager.GetString("InvalidEqualityComparerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters number..
        /// </summary>
        internal static string InvalidParametersNumber {
            get {
                return ResourceManager.GetString("InvalidParametersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property type..
        /// </summary>
        internal static string InvalidPropertyType {
            get {
                return ResourceManager.GetString("InvalidPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger configuration is not valid..
        /// </summary>
        internal static string InvalidSwaggerConfiguration {
            get {
                return ResourceManager.GetString("InvalidSwaggerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seed data..
        /// </summary>
        internal static string IvalidSeedData {
            get {
                return ResourceManager.GetString("IvalidSeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template text is in invalid state. Text placeholder is &apos;null&apos;, but text placeholders number is greater than 0, which leads to impossibility of text formatting..
        /// </summary>
        internal static string MessageTemplateTextInInvalidState {
            get {
                return ResourceManager.GetString("MessageTemplateTextInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder does not exist. Template name: &apos;{0}&apos;; Culture name: &apos;{1}&apos;; Placeholder name: &apos;{2}&apos;..
        /// </summary>
        internal static string PlaceholderNotExists {
            get {
                return ResourceManager.GetString("PlaceholderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not declared in &apos;{1}&apos; type..
        /// </summary>
        internal static string PropertyNotDeclared {
            get {
                return ResourceManager.GetString("PropertyNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;TemplateText&apos; or &apos;TemplateTextSourcePath&apos; is required..
        /// </summary>
        internal static string TemplateTextOrSourcePathIsRequired {
            get {
                return ResourceManager.GetString("TemplateTextOrSourcePathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; value can not be less or equal to 0..
        /// </summary>
        internal static string ValueCanNotBeLessOrEqualToZero {
            get {
                return ResourceManager.GetString("ValueCanNotBeLessOrEqualToZero", resourceCulture);
            }
        }
    }
}
