//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Localization.ExceptionsHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradise.Localization.ExceptionsHandling.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application secret is missing. Check the configuration..
        /// </summary>
        public static string ApplicationSecretMissing {
            get {
                return ResourceManager.GetString("ApplicationSecretMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;TemplateText&apos; or &apos;TemplateTextSourcePath&apos; is required..
        /// </summary>
        public static string EitherTemplateTextOrTemplateTextSourcePathIsRequired {
            get {
                return ResourceManager.GetString("EitherTemplateTextOrTemplateTextSourcePathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template subject is in invalid state. Subject placeholder is &apos;null&apos;, but text placeholders number is greater than 0, which leads to impossibility of subject formatting..
        /// </summary>
        public static string EmailTemplateSubjectInInvalidState {
            get {
                return ResourceManager.GetString("EmailTemplateSubjectInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize into the instance of type &apos;{0}&apos;..
        /// </summary>
        public static string FailedToDeserialize {
            get {
                return ResourceManager.GetString("FailedToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid email address..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type &apos;{0}&apos; is in invalid state. Column name: &apos;{1}&apos;, value: &apos;{2}&apos;..
        /// </summary>
        public static string InvalidEntityState {
            get {
                return ResourceManager.GetString("InvalidEntityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information: .
        /// </summary>
        public static string InvalidEntityStateAdditionalInformation {
            get {
                return ResourceManager.GetString("InvalidEntityStateAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment name is not valid. Available options are: {0}..
        /// </summary>
        public static string InvalidEnvironmentName {
            get {
                return ResourceManager.GetString("InvalidEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters number..
        /// </summary>
        public static string InvalidParametersNumber {
            get {
                return ResourceManager.GetString("InvalidParametersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InvalidSwaggerConfiguration {
            get {
                return ResourceManager.GetString("InvalidSwaggerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seed data..
        /// </summary>
        public static string IvalidSeedData {
            get {
                return ResourceManager.GetString("IvalidSeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template text is in invalid state. Text placeholder is &apos;null&apos;, but text placeholders number is greater than 0, which leads to impossibility of text formatting..
        /// </summary>
        public static string MessageTemplateTextInInvalidState {
            get {
                return ResourceManager.GetString("MessageTemplateTextInInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder does not exist. Template name: &apos;{0}&apos;; Culture name: &apos;{1}&apos;; Placeholder name: &apos;{2}&apos;..
        /// </summary>
        public static string PlaceholderNotExists {
            get {
                return ResourceManager.GetString("PlaceholderNotExists", resourceCulture);
            }
        }
    }
}
