//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Localization.ErrorsHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradise.Localization.ErrorsHandling.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the resource is forbidden..
        /// </summary>
        public static string AccessForbidden {
            get {
                return ResourceManager.GetString("AccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is already taken..
        /// </summary>
        public static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message recipients list is empty..
        /// </summary>
        public static string EmptyRecipientsList {
            get {
                return ResourceManager.GetString("EmptyRecipientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic concurrency failure, the object has been modified..
        /// </summary>
        public static string IdentityConcurrencyFailure {
            get {
                return ResourceManager.GetString("IdentityConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string IdentityDefaultError {
            get {
                return ResourceManager.GetString("IdentityDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        public static string IdentityDuplicateEmail {
            get {
                return ResourceManager.GetString("IdentityDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string IdentityDuplicateRoleName {
            get {
                return ResourceManager.GetString("IdentityDuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-name &apos;{0}&apos; is already taken..
        /// </summary>
        public static string IdentityDuplicateUserName {
            get {
                return ResourceManager.GetString("IdentityDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is invalid..
        /// </summary>
        public static string IdentityInvalidEmail {
            get {
                return ResourceManager.GetString("IdentityInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must derive from {1}&apos;&lt;{2}&gt;&apos;..
        /// </summary>
        public static string IdentityInvalidManagerType {
            get {
                return ResourceManager.GetString("IdentityInvalidManagerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided PasswordHasherCompatibilityMode is invalid..
        /// </summary>
        public static string IdentityInvalidPasswordHasherCompatibilityMode {
            get {
                return ResourceManager.GetString("IdentityInvalidPasswordHasherCompatibilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The iteration count must be a positive integer..
        /// </summary>
        public static string IdentityInvalidPasswordHasherIterationCount {
            get {
                return ResourceManager.GetString("IdentityInvalidPasswordHasherIterationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string IdentityInvalidRoleName {
            get {
                return ResourceManager.GetString("IdentityInvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string IdentityInvalidToken {
            get {
                return ResourceManager.GetString("IdentityInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-name &apos;{0}&apos; is invalid, can only contain letters or digits..
        /// </summary>
        public static string IdentityInvalidUserName {
            get {
                return ResourceManager.GetString("IdentityInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this login already exists..
        /// </summary>
        public static string IdentityLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("IdentityLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIdentity must be called on the service collection..
        /// </summary>
        public static string IdentityMustCallAddIdentity {
            get {
                return ResourceManager.GetString("IdentityMustCallAddIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IPersonalDataProtector service was registered, this is required when ProtectPersonalData = true..
        /// </summary>
        public static string IdentityNoPersonalDataProtector {
            get {
                return ResourceManager.GetString("IdentityNoPersonalDataProtector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No RoleType was specified, try AddRoles&lt;TRole&gt;()..
        /// </summary>
        public static string IdentityNoRoleType {
            get {
                return ResourceManager.GetString("IdentityNoRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IUserTwoFactorTokenProvider&lt;{0}&gt; named &apos;{1}&apos; is registered..
        /// </summary>
        public static string IdentityNoTokenProvider {
            get {
                return ResourceManager.GetString("IdentityNoTokenProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User security stamp cannot be null..
        /// </summary>
        public static string IdentityNullSecurityStamp {
            get {
                return ResourceManager.GetString("IdentityNullSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string IdentityPasswordMismatch {
            get {
                return ResourceManager.GetString("IdentityPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        public static string IdentityPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        public static string IdentityPasswordRequiresLower {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non-alphanumeric character..
        /// </summary>
        public static string IdentityPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must use at least {0} different characters..
        /// </summary>
        public static string IdentityPasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        public static string IdentityPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least {0} characters..
        /// </summary>
        public static string IdentityPasswordTooShort {
            get {
                return ResourceManager.GetString("IdentityPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code redemption failed..
        /// </summary>
        public static string IdentityRecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("IdentityRecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; does not exist..
        /// </summary>
        public static string IdentityRoleNotFound {
            get {
                return ResourceManager.GetString("IdentityRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IProtectedUserStore&lt;TUser&gt;; which is required when ProtectPersonalData = true..
        /// </summary>
        public static string IdentityStoreNotIProtectedUserStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIProtectedUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableRoleStore&lt;TRole&gt;..
        /// </summary>
        public static string IdentityStoreNotIQueryableRoleStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIQueryableRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IQueryableUserStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIQueryableUserStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIQueryableUserStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IRoleClaimStore&lt;TRole&gt;..
        /// </summary>
        public static string IdentityStoreNotIRoleClaimStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIRoleClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserAuthenticationTokenStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserAuthenticationTokenStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserAuthenticationTokenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserAuthenticatorKeyStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserAuthenticatorKeyStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserAuthenticatorKeyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserClaimStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserClaimStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserClaimStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserConfirmationStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserConfirmationStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserConfirmationStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserEmailStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserEmailStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserEmailStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserLockoutStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserLockoutStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserLockoutStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserLoginStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserLoginStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserLoginStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserPasswordStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserPasswordStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserPasswordStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserPhoneNumberStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserPhoneNumberStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserPhoneNumberStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserRoleStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserRoleStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserRoleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserSecurityStampStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserSecurityStampStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserSecurityStampStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserTwoFactorRecoveryCodeStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserTwoFactorRecoveryCodeStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserTwoFactorRecoveryCodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store does not implement IUserTwoFactorStore&lt;TUser&gt;..
        /// </summary>
        public static string IdentityStoreNotIUserTwoFactorStore {
            get {
                return ResourceManager.GetString("IdentityStoreNotIUserTwoFactorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password set..
        /// </summary>
        public static string IdentityUserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("IdentityUserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already in role &apos;{0}&apos;..
        /// </summary>
        public static string IdentityUserAlreadyInRole {
            get {
                return ResourceManager.GetString("IdentityUserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        public static string IdentityUserLockedOut {
            get {
                return ResourceManager.GetString("IdentityUserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout is not enabled for this user..
        /// </summary>
        public static string IdentityUserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("IdentityUserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        public static string IdentityUserNameNotFound {
            get {
                return ResourceManager.GetString("IdentityUserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in role &apos;{0}&apos;..
        /// </summary>
        public static string IdentityUserNotInRole {
            get {
                return ResourceManager.GetString("IdentityUserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP configuration is not valid..
        /// </summary>
        public static string InvalidSmtpConfiguration {
            get {
                return ResourceManager.GetString("InvalidSmtpConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with the specified name &apos;{0}&apos; and culture &apos;{1}&apos; already exists..
        /// </summary>
        public static string MessageTemplateAlreadyExists {
            get {
                return ResourceManager.GetString("MessageTemplateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MessageTemplateEmptyText {
            get {
                return ResourceManager.GetString("MessageTemplateEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string MessageTemplateIdNotFound {
            get {
                return ResourceManager.GetString("MessageTemplateIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MessageTemplateInvalidPlaceholdersNumber {
            get {
                return ResourceManager.GetString("MessageTemplateInvalidPlaceholdersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template name is a null or empty string..
        /// </summary>
        public static string MessageTemplateMissingName {
            get {
                return ResourceManager.GetString("MessageTemplateMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MessageTemplateMissingPlaceholder {
            get {
                return ResourceManager.GetString("MessageTemplateMissingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with the name &apos;{0}&apos; and culture name &apos;{1}&apos; does not exist..
        /// </summary>
        public static string MessageTemplateNotFound {
            get {
                return ResourceManager.GetString("MessageTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is outdated. Generate a new one..
        /// </summary>
        public static string OutdatedToken {
            get {
                return ResourceManager.GetString("OutdatedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing password..
        /// </summary>
        public static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not match its confirmation value..
        /// </summary>
        public static string PasswordNotMatchConfirmation {
            get {
                return ResourceManager.GetString("PasswordNotMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string RoleIdNotFound {
            get {
                return ResourceManager.GetString("RoleIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email address was provided to send messages from..
        /// </summary>
        public static string SenderEmailIsMissing {
            get {
                return ResourceManager.GetString("SenderEmailIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token owner does not exist..
        /// </summary>
        public static string TokenOwnerNotExists {
            get {
                return ResourceManager.GetString("TokenOwnerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string UnauthorizedUser {
            get {
                return ResourceManager.GetString("UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion request has exceeded its lifetime ({0})..
        /// </summary>
        public static string UserDeletionRequestExpired {
            get {
                return ResourceManager.GetString("UserDeletionRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is already confirmed..
        /// </summary>
        public static string UserEmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("UserEmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is not confirmed..
        /// </summary>
        public static string UserEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserEmailNotFound {
            get {
                return ResourceManager.GetString("UserEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user does not exist or password is incorrect..
        /// </summary>
        public static string UserNotFoundOrPasswordMismatch {
            get {
                return ResourceManager.GetString("UserNotFoundOrPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; is not pending deletion..
        /// </summary>
        public static string UserNotPendingDeletion {
            get {
                return ResourceManager.GetString("UserNotPendingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with phone number &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserPhoneNumberNotFound {
            get {
                return ResourceManager.GetString("UserPhoneNumberNotFound", resourceCulture);
            }
        }
    }
}
