trigger:
- main
- staging

pool:
  vmImage: ubuntu-latest

variables:
  - name: 'buildConfiguration'
    readonly: true
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: 'Release'
    ${{ else }}:
      value: 'Debug'

steps:

- task: UseDotNet@2
  displayName: 'Download .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    arguments: --collect:"Code Coverage"

- task: DotNetCoreCLI@2
  displayName: 'Publish Web API project'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/WebApi'
    modifyOutputPath: true
    zipAfterPublish: true
    publishWebProjects: false
    projects: '**/*.WebApi.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish Worker Service project'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Maintenance'
    modifyOutputPath: true
    zipAfterPublish: true
    publishWebProjects: false
    projects: '**/*.Maintenance.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Web API build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/WebApi'
    ArtifactName: 'WebApi'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Worker Service build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Maintenance'
    ArtifactName: 'Maintenance'
    publishLocation: 'Container'