trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:

  - group: 'maintenance-main'

  - name: 'buildConfiguration'
    value: 'Debug'
    readonly: true

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    arguments: --collect:"XPlat Code Coverage"

- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage report'
  inputs:
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: DotNetCoreCLI@2
  displayName: 'Publish Web API project'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: true
    zipAfterPublish: true
    publishWebProjects: false
    projects: '**/*.WebApi.csproj'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Web API build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'WebApi'
    publishLocation: 'Container'

- task: Docker@2
  displayName: 'Build and upload Maintenance project'
  inputs:
    containerRegistry: '$(containerRegistryConnectionName)'
    repository: '$(repositoryName)'
    command: 'buildAndPush'
    Dockerfile: '**/*.Maintenance/Dockerfile'
    buildContext: '.'