//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Localization.ExceptionHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradise.Localization.ExceptionHandling.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message recipients list is empty..
        /// </summary>
        internal static string EmptyRecipientsList {
            get {
                return ResourceManager.GetString("EmptyRecipientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateInstanceOfType {
            get {
                return ResourceManager.GetString("FailedToCreateInstanceOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize into the instance of type &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToDeserialize {
            get {
                return ResourceManager.GetString("FailedToDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier is already assigned and cannot be modified..
        /// </summary>
        internal static string IdentityIsAlreadyAssigned {
            get {
                return ResourceManager.GetString("IdentityIsAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object of type &apos;{0}&apos; is in an invalid state. Property name: &apos;{1}&apos;, value: &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidDomainState {
            get {
                return ResourceManager.GetString("InvalidDomainState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Additional information:.
        /// </summary>
        internal static string InvalidDomainStateAdditionalInformation {
            get {
                return ResourceManager.GetString("InvalidDomainStateAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment name &apos;{0}&apos; is not valid. Available options are: {1}..
        /// </summary>
        internal static string InvalidEnvironmentName {
            get {
                return ResourceManager.GetString("InvalidEnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seed data..
        /// </summary>
        internal static string InvalidSeedData {
            get {
                return ResourceManager.GetString("InvalidSeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SMTP configuration..
        /// </summary>
        internal static string InvalidSmtpConfiguration {
            get {
                return ResourceManager.GetString("InvalidSmtpConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template formattable text property is invalid. Text placeholder is &apos;null&apos;, but the text placeholders&apos; number is greater than 0, which makes it impossible to perform text formatting..
        /// </summary>
        internal static string MessageTemplateFormattableTextIsInvalid {
            get {
                return ResourceManager.GetString("MessageTemplateFormattableTextIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters number..
        /// </summary>
        internal static string MessageTemplateInvalidParametersNumber {
            get {
                return ResourceManager.GetString("MessageTemplateInvalidParametersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template formattable text property does not contain the specified number of placeholders. Expected: {0}, but was: {1}..
        /// </summary>
        internal static string MessageTemplateInvalidPlaceholdersNumber {
            get {
                return ResourceManager.GetString("MessageTemplateInvalidPlaceholdersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with the name &apos;{0}&apos; and culture &apos;{1}&apos; does not exist..
        /// </summary>
        internal static string MessageTemplateNotFound {
            get {
                return ResourceManager.GetString("MessageTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder does not exist. Template name: &apos;{0}&apos;; Culture name: &apos;{1}&apos;; Placeholder name: &apos;{2}&apos;..
        /// </summary>
        internal static string MessageTemplatePlaceholderNotExists {
            get {
                return ResourceManager.GetString("MessageTemplatePlaceholderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;TemplateText&apos; or &apos;TemplateTextSourcePath&apos; is required..
        /// </summary>
        internal static string MessageTemplateTemplateTextOrSourcePathIsRequired {
            get {
                return ResourceManager.GetString("MessageTemplateTemplateTextOrSourcePathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; sub-string is not present in the following string: &apos;{1}&apos;..
        /// </summary>
        internal static string MissingSubstring {
            get {
                return ResourceManager.GetString("MissingSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid property type..
        /// </summary>
        internal static string PropertyHasInvalidType {
            get {
                return ResourceManager.GetString("PropertyHasInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not declared in type &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyNotDeclared {
            get {
                return ResourceManager.GetString("PropertyNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the following properties is required: {0}..
        /// </summary>
        internal static string RequiredAtLeastOne {
            get {
                return ResourceManager.GetString("RequiredAtLeastOne", resourceCulture);
            }
        }
    }
}
