<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Code\Common\Paradise.Models\Paradise.Models.csproj" />
		<ProjectReference Include="..\..\..\Code\Core\Paradise.ApplicationLogic.Infrastructure.Domain\Paradise.ApplicationLogic.Infrastructure.Domain.csproj" />
		<ProjectReference Include="..\..\..\Code\Core\Paradise.ApplicationLogic.Infrastructure\Paradise.ApplicationLogic.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Code\Core\Paradise.DataAccess\Paradise.DataAccess.csproj" />
		<ProjectReference Include="..\..\..\Code\Core\Paradise.Domain.Base\Paradise.Domain.Base.csproj" />
		<ProjectReference Include="..\..\..\Code\Web\Paradise.WebApi.Base\Paradise.WebApi.Base.csproj" />
	</ItemGroup>

</Project>