IF NOT EXISTS (SELECT * FROM [master].sys.sql_logins WHERE [name] = '$(LOGIN)')
CREATE LOGIN [$(LOGIN)] WITH PASSWORD=N'$(PASSWORD)', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO

IF IS_SRVROLEMEMBER('dbcreator', '$(LOGIN)') = 0
ALTER SERVER ROLE [dbcreator] ADD MEMBER [$(LOGIN)];
GO