<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Code\Core\Paradise.ApplicationLogic.Infrastructure\Paradise.ApplicationLogic.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Supplemental\Paradise.Tests.Extensibility\Paradise.Tests.Extensibility.csproj" />
		<ProjectReference Include="..\..\..\Supplemental\Paradise.Tests.Serialization\Paradise.Tests.Serialization.csproj" />
	</ItemGroup>

</Project>