<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Code\Core\Paradise.ApplicationLogic.Infrastructure.Domain\Paradise.ApplicationLogic.Infrastructure.Domain.csproj" />
		<ProjectReference Include="..\..\..\Supplemental\Paradise.Tests.Serialization\Paradise.Tests.Serialization.csproj" />
		<ProjectReference Include="..\..\..\Supplemental\Paradise.Tests.Surrogates\Paradise.Tests.Surrogates.csproj" />
	</ItemGroup>

</Project>