trigger: none
pr: none

pool:
  vmImage: windows-latest

parameters:
  - name: verbosity
    displayName: 'Verbosity level'
    type: string
    default: 'minimal'
    values:
      - quiet
      - minimal
      - normal
      - detailed
      - diagnostic

  - name: configuration
    displayName: 'Build configuration'
    type: string
    default: 'Release'
    values:
      - Release
      - Debug

jobs:
- job: BuildTestAndPublishArtifact
  displayName: 'Build, test & publish artifact'
  steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: '0'

  - template: Templates/build-flow.yml
    parameters:
      verbosity: '${{ parameters.verbosity }}'
      configuration: '${{ parameters.configuration }}'

  - template: Templates/publish-flow.yml
    parameters:
      verbosity: '${{ parameters.verbosity }}'
      configuration: '${{ parameters.configuration }}'
      projectDisplayName: 'Web API'
      projectName: '**/*.WebApi.csproj'
      outputFolder: 'WebApi'

  - template: Templates/publish-flow.yml
    parameters:
      verbosity: '${{ parameters.verbosity }}'
      configuration: '${{ parameters.configuration }}'
      projectDisplayName: 'Maintenance'
      projectName: '**/*.Maintenance.csproj'
      outputFolder: 'Maintenance'