<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<InternalsVisibleTo Include="$(AssemblyName).Tests.Unit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\Paradise.ApplicationLogic\Paradise.ApplicationLogic.csproj" />
		<ProjectReference Include="..\Paradise.WebApi.Base\Paradise.WebApi.Base.csproj" />
	</ItemGroup>

</Project>