<Project>

	<PropertyGroup>
		<_ParentProps>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</_ParentProps>

		<_ExcludedProjects>Paradise.Tests.Doubles;Paradise.Tests.Extensibility;Paradise.Tests.Fixtures;Paradise.Tests.Serialization</_ExcludedProjects>
	</PropertyGroup>

	<Import Project="$(_ParentProps)" Condition="Exists($(_ParentProps))" />

	<Import Project="Directory.Build.Tests.props" Condition="!$(_ExcludedProjects.Contains('$(MSBuildProjectName)'))"/>

</Project>