//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Localization.ErrorHandling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradise.Localization.ErrorHandling.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access forbidden..
        /// </summary>
        public static string AccessForbidden {
            get {
                return ResourceManager.GetString("AccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown failure has occurred..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address &apos;{0}&apos; is in use..
        /// </summary>
        public static string DuplicateEmailAddress {
            get {
                return ResourceManager.GetString("DuplicateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is in use..
        /// </summary>
        public static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is in use..
        /// </summary>
        public static string DuplicateRoleName {
            get {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-name &apos;{0}&apos; is in use..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; does not match it&apos;s confirmation - &apos;{1}&apos;..
        /// </summary>
        public static string EmailAddressNotMatchConfirmation {
            get {
                return ResourceManager.GetString("EmailAddressNotMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidRoleName {
            get {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-name &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with the name &apos;{0}&apos; and culture &apos;{1}&apos; already exists..
        /// </summary>
        public static string MessageTemplateAlreadyExists {
            get {
                return ResourceManager.GetString("MessageTemplateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MessageTemplateEmptyText {
            get {
                return ResourceManager.GetString("MessageTemplateEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string MessageTemplateIdNotFound {
            get {
                return ResourceManager.GetString("MessageTemplateIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template name is a null or empty string..
        /// </summary>
        public static string MessageTemplateMissingName {
            get {
                return ResourceManager.GetString("MessageTemplateMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template with the name &apos;{0}&apos; and culture &apos;{1}&apos; does not exist..
        /// </summary>
        public static string MessageTemplateNotFound {
            get {
                return ResourceManager.GetString("MessageTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is outdated. Generate a new one..
        /// </summary>
        public static string OutdatedToken {
            get {
                return ResourceManager.GetString("OutdatedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing password..
        /// </summary>
        public static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password value does not match it&apos;s confirmation value..
        /// </summary>
        public static string PasswordNotMatchConfirmation {
            get {
                return ResourceManager.GetString("PasswordNotMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string RoleIdNotFound {
            get {
                return ResourceManager.GetString("RoleIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion request has exceeded its lifetime ({0})..
        /// </summary>
        public static string UserDeletionRequestExpired {
            get {
                return ResourceManager.GetString("UserDeletionRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is already confirmed..
        /// </summary>
        public static string UserEmailAddressAlreadyConfirmed {
            get {
                return ResourceManager.GetString("UserEmailAddressAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address &apos;{0}&apos; is not confirmed..
        /// </summary>
        public static string UserEmailAddressNotConfirmed {
            get {
                return ResourceManager.GetString("UserEmailAddressNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email address &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserEmailAddressNotFound {
            get {
                return ResourceManager.GetString("UserEmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked out..
        /// </summary>
        public static string UserLockedOut {
            get {
                return ResourceManager.GetString("UserLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user does not exist or password is incorrect..
        /// </summary>
        public static string UserNotFoundOrPasswordMismatch {
            get {
                return ResourceManager.GetString("UserNotFoundOrPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; is not pending deletion..
        /// </summary>
        public static string UserNotPendingDeletion {
            get {
                return ResourceManager.GetString("UserNotPendingDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with phone number &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserPhoneNumberNotFound {
            get {
                return ResourceManager.GetString("UserPhoneNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token with Id &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserRefreshTokenIdNotFound {
            get {
                return ResourceManager.GetString("UserRefreshTokenIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized..
        /// </summary>
        public static string UserUnauthorized {
            get {
                return ResourceManager.GetString("UserUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with user-name &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserUserNameNotFound {
            get {
                return ResourceManager.GetString("UserUserNameNotFound", resourceCulture);
            }
        }
    }
}
