// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Paradise.DataAccess.Database;

#nullable disable

namespace Paradise.DataAccess.Migrations.Application;

[DbContext(typeof(ApplicationContext))]
partial class ApplicationContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Paradise.ApplicationLogic.Domain.MessageTemplates.EmailTemplate", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("Created")
                .HasColumnType("datetime2");

            b.Property<int?>("Culture")
                .HasColumnType("int");

            b.Property<bool>("IsBodyHtml")
                .HasColumnType("bit");

            b.Property<DateTime>("Modified")
                .HasColumnType("datetime2");

            b.Property<string>("PlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("PlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("Subject")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("SubjectPlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("SubjectPlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("TemplateName")
                .IsRequired()
                .HasColumnType("nvarchar(450)");

            b.Property<string>("TemplateText")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.HasIndex("TemplateName", "Culture")
                .IsUnique()
                .HasFilter("[Culture] IS NOT NULL");

            b.ToTable("EmailTemplates", (string)null);
        });
#pragma warning restore 612, 618
    }
}