// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Paradise.DataAccess.Database.Migrations.ApplicationLogic.Infrastructure.Domain;

[DbContext(typeof(InfrastructureContext))]
partial class InfrastructureContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDefaultSchema("infrastructure")
            .HasAnnotation("ProductVersion", "10.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.UseIdentityColumns();

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<int>("Id")
                .UseIdentityColumn();

            b.Property<string>("FriendlyName")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Xml")
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("DataProtectionKeys", "infrastructure");
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.MessageTemplates.EmailTemplate", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTimeOffset>("Created")
                .HasColumnType("datetimeoffset");

            b.Property<int?>("Culture")
                .HasColumnType("int");

            b.Property<bool>("IsBodyHtml")
                .HasColumnType("bit");

            b.Property<DateTimeOffset>("Modified")
                .HasColumnType("datetimeoffset");

            b.Property<string>("PlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("PlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("Subject")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("SubjectPlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("SubjectPlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("TemplateName")
                .IsRequired()
                .HasColumnType("nvarchar(450)");

            b.Property<string>("TemplateText")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.HasIndex("TemplateName", "Culture")
                .IsUnique()
                .HasFilter("[Culture] IS NOT NULL");

            b.ToTable("EmailTemplates", "infrastructure");
        });
    }
}