// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Diagnostics.CodeAnalysis;

namespace Paradise.DataAccess.Database.Migrations;

[DbContext(typeof(ApplicationContext))]
[ExcludeFromCodeCoverage]
partial class ApplicationContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.UseIdentityColumns();

        modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<int>("Id")
                .UseIdentityColumn();

            b.Property<string>("FriendlyName")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Xml")
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.ToTable("DataProtectionKeys", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<int>("Id")
                .UseIdentityColumn();

            b.Property<string>("ClaimType")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ClaimValue")
                .HasColumnType("nvarchar(max)");

            b.Property<Guid>("RoleId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("RoleId");

            b.ToTable("AspNetRoleClaims", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            b.Property<int>("Id")
                .UseIdentityColumn();

            b.Property<string>("ClaimType")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ClaimValue")
                .HasColumnType("nvarchar(max)");

            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserClaims", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.Property<string>("LoginProvider")
                .HasColumnType("nvarchar(450)");

            b.Property<string>("ProviderKey")
                .HasColumnType("nvarchar(450)");

            b.Property<string>("ProviderDisplayName")
                .HasColumnType("nvarchar(max)");

            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("LoginProvider", "ProviderKey");

            b.HasIndex("UserId");

            b.ToTable("AspNetUserLogins", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid>("RoleId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("UserId", "RoleId");

            b.HasIndex("RoleId");

            b.ToTable("AspNetUserRoles", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("LoginProvider")
                .HasColumnType("nvarchar(450)");

            b.Property<string>("Name")
                .HasColumnType("nvarchar(450)");

            b.Property<string>("Value")
                .HasColumnType("nvarchar(max)");

            b.HasKey("UserId", "LoginProvider", "Name");

            b.ToTable("AspNetUserTokens", "infrastructure");
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.Role", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("nvarchar(max)");

            b.Property<DateTimeOffset>("Created")
                .HasColumnType("datetimeoffset");

            b.Property<bool>("IsDefault")
                .HasColumnType("bit");

            b.Property<DateTimeOffset>("Modified")
                .HasColumnType("datetimeoffset");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<string>("NormalizedName")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.HasKey("Id");

            b.HasIndex("NormalizedName")
                .IsUnique()
                .HasDatabaseName("RoleNameIndex")
                .HasFilter("[NormalizedName] IS NOT NULL");

            b.ToTable("AspNetRoles", "infrastructure");
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<int>("AccessFailedCount")
                .HasColumnType("int");

            b.Property<string>("ConcurrencyStamp")
                .IsConcurrencyToken()
                .HasColumnType("nvarchar(max)");

            b.Property<DateTimeOffset>("Created")
                .HasColumnType("datetimeoffset");

            b.Property<DateTimeOffset?>("DeletionRequestSubmitted")
                .HasColumnType("datetimeoffset");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<bool>("EmailConfirmed")
                .HasColumnType("bit");

            b.Property<bool>("LockoutEnabled")
                .HasColumnType("bit");

            b.Property<DateTimeOffset?>("LockoutEnd")
                .HasColumnType("datetimeoffset");

            b.Property<DateTimeOffset>("Modified")
                .HasColumnType("datetimeoffset");

            b.Property<string>("NormalizedEmail")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<string>("NormalizedUserName")
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.Property<string>("PasswordHash")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("PhoneNumber")
                .HasColumnType("nvarchar(max)");

            b.Property<bool>("PhoneNumberConfirmed")
                .HasColumnType("bit");

            b.Property<string>("SecurityStamp")
                .HasColumnType("nvarchar(max)");

            b.Property<bool>("TwoFactorEnabled")
                .HasColumnType("bit");

            b.Property<string>("UserName")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("nvarchar(256)");

            b.HasKey("Id");

            b.HasIndex("NormalizedEmail")
                .HasDatabaseName("EmailIndex");

            b.HasIndex("NormalizedUserName")
                .IsUnique()
                .HasDatabaseName("UserNameIndex")
                .HasFilter("[NormalizedUserName] IS NOT NULL");

            b.ToTable("AspNetUsers", "infrastructure");
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.UserRefreshToken", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTimeOffset>("Created")
                .HasColumnType("datetimeoffset");

            b.Property<DateTimeOffset>("ExpiryDateUtc")
                .HasColumnType("datetimeoffset");

            b.Property<bool>("IsActive")
                .HasColumnType("bit");

            b.Property<DateTimeOffset>("Modified")
                .HasColumnType("datetimeoffset");

            b.Property<Guid>("OwnerId")
                .HasColumnType("uniqueidentifier");

            b.HasKey("Id");

            b.HasIndex("OwnerId");

            b.ToTable("UserRefreshTokens", "infrastructure");
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.MessageTemplates.EmailTemplate", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTimeOffset>("Created")
                .HasColumnType("datetimeoffset");

            b.Property<int?>("Culture")
                .HasColumnType("int");

            b.Property<bool>("IsBodyHtml")
                .HasColumnType("bit");

            b.Property<DateTimeOffset>("Modified")
                .HasColumnType("datetimeoffset");

            b.Property<string>("PlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("PlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("Subject")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.Property<string>("SubjectPlaceholderName")
                .HasColumnType("nvarchar(max)");

            b.Property<int>("SubjectPlaceholdersNumber")
                .HasColumnType("int");

            b.Property<string>("TemplateName")
                .IsRequired()
                .HasColumnType("nvarchar(450)");

            b.Property<string>("TemplateText")
                .IsRequired()
                .HasColumnType("nvarchar(max)");

            b.HasKey("Id");

            b.HasIndex("TemplateName", "Culture")
                .IsUnique()
                .HasFilter("[Culture] IS NOT NULL");

            b.ToTable("EmailTemplates", "infrastructure");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.Role", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.Role", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.UserRefreshToken", b =>
        {
            b.HasOne("Paradise.ApplicationLogic.Infrastructure.Domain.Identity.User", null)
                .WithMany()
                .HasForeignKey("OwnerId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
    }
}