version: '3.4'

services:

  mssql:
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      LOGIN: ${MSSQL_USER_LOGIN}
      PASSWORD: ${MSSQL_USER_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./Scripts/MS SQL Server/Shell/:/Scripts/Shell/:ro
      - ./Scripts/MS SQL Server/SQL/:/Scripts/SQL/:ro
    entrypoint:
      - /Scripts/Shell/Entrypoint.sh

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_NAME}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - Logging__Console__FormatterName=${LOGGING_FORMAT}
      - ConnectionStrings__ApplicationConnectionString=${APPLICATION_CONNECTION_STRING}
      - ConnectionStrings__DomainConnectionString=${DOMAIN_CONNECTION_STRING}
      - SmtpOptions__Credentials__Password=${SMTP_USERNAME}
      - SmtpOptions__Credentials__UserName=${SMTP_PASSWORD}
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./Scripts/WebApi/Shell/:/Scripts/Shell/:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/DataProtection-Keys/Paradise.WebApi:/root/.aspnet/DataProtection-Keys

  maintenance:
    environment:
      - DOTNET_ENVIRONMENT=${ENVIRONMENT_NAME}
      - Logging__Console__FormatterName=${LOGGING_FORMAT}
      - ConnectionStrings__ApplicationConnectionString=${APPLICATION_CONNECTION_STRING}
      - ConnectionStrings__DomainConnectionString=${DOMAIN_CONNECTION_STRING}
      - SmtpOptions__Credentials__Password=${SMTP_USERNAME}
      - SmtpOptions__Credentials__UserName=${SMTP_PASSWORD}
    volumes:
      - ${APPDATA}/ASP.NET/DataProtection-Keys/Paradise.Maintenance:/root/.aspnet/DataProtection-Keys