<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<None Remove="Data\HTML\EmailAddressChangedNotification.html" />
		<None Remove="Data\HTML\EmailAddressChangeLink.html" />
		<None Remove="Data\HTML\EmailAddressChangingNotification.html" />
		<None Remove="Data\HTML\EmailAddressConfirmationLink.html" />
		<None Remove="Data\HTML\PasswordChangedNotification.html" />
		<None Remove="Data\HTML\PasswordChangeLink.html" />
		<None Remove="Data\HTML\TwoFactorVerification.html" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Data\JSON\DomainData.json" />
		<None Remove="Data\JSON\InfrastructureData.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Data\HTML\EmailAddressChangedNotification.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\EmailAddressChangeLink.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\EmailAddressChangingNotification.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\EmailAddressConfirmationLink.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\PasswordChangedNotification.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\PasswordChangeLink.html" CopyToOutputDirectory="Always" />
		<Content Include="Data\HTML\TwoFactorVerification.html" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Data\JSON\DomainData.json" CopyToOutputDirectory="Always" />
		<Content Include="Data\JSON\InfrastructureData.json" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\Paradise.Primitives\Paradise.Primitives.csproj" />
	</ItemGroup>

</Project>